packageExtensions:
  '@angular-eslint/eslint-plugin-template@*':
    dependencies:
      '@typescript-eslint/types': '*'
      '@typescript-eslint/utils': '*'
  '@angular-eslint/eslint-plugin@*':
    dependencies:
      '@typescript-eslint/utils': '*'
  '@nx/devkit@*':
    dependencies:
      '@angular-devkit/architect': '*'
